version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build application Docker image
          command: |
            docker build -t $CIRCLE_PROJECT_REPONAME .
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
              docker tag $CIRCLE_PROJECT_REPONAME "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BUILD_NUM}"
              docker tag $CIRCLE_PROJECT_REPONAME "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:latest"
              docker push "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:latest"
            fi
workflows:
  version: 2
  main-workflow:
    jobs:
      - build:
          context: Docker Credentials
